apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abrp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: teslamate
  destination:
    namespace: teslamate
    server: {{ .Values.spec.destination.server }}
  source:
    path: abrp/overlays/prod
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
