apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: teslamate
  destination:
    namespace: teslamate
    server: {{ .Values.spec.destination.server }}
  source:
    path: ingress
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
