apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
resources:
  - ../../base
configMapGenerator:
  - envs:
      - config.env
    name: abrp-config-env
