apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: docker.io/teslamate/teslamate
    newTag: '1.31.1'
resources:
  - ../../base
configMapGenerator:
  - name: teslamate-config-env
    envs:
      - config.env
