apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: prod
images:
  - name: docker.io/teslamate/teslamate
    newTag: 1.27.3
bases:
  - ../../base
patchesJson6902:
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          cfargotunnel.com/cluster-tunnel: k3s-xmple-io
          cfargotunnel.com/fqdn: teslamate.xmple.io
    target:
      version: v1
      kind: Service
      name: teslamate
configMapGenerator:
  - name: teslamate-config-env
    envs:
      - config.env
