apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/part-of: teslamate
resources:
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  #- ingress.yaml
  - httproute.yaml