apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-secrets-env
    template:
      engineVersion: v2
      type: Opaque
      data:
        DATABASE_HOST: "{{ .databaseHost }}"
        DATABASE_NAME: "{{ .databaseName }}"
        DATABASE_USER: "{{ .databaseUser }}"
        DATABASE_PASS: "{{ .databasePass }}"
  data:
    - secretKey: databaseHost
      remoteRef:
        key: secret/teslamate/postgres
        property: HOSTNAME
    - secretKey: databaseName
      remoteRef:
        key: secret/teslamate/postgres
        property: DATABASE
    - secretKey: databaseUser
      remoteRef:
        key: secret/teslamate/postgres
        property: USERNAME
    - secretKey: databasePass
      remoteRef:
        key: secret/teslamate/postgres
        property: PASSWORD
