apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: docker.io/teslamate/grafana
    newTag: '2.0.0'
resources:
  - ../../base
configMapGenerator:
  - name: grafana-config-env
    envs:
      - config.env
