apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: docker.io/teslamate/grafana
    newTag: '1.27'
resources:
  - ../../base
patches:
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          cfargotunnel.com/cluster-tunnel: k3s-xmple-io
          cfargotunnel.com/fqdn: teslamate.xmple.io
    target:
      version: v1
      kind: Service
      name: teslamate
configMapGenerator:
  - name: grafana-config-env
    envs:
      - config.env
