apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teslamate-tls
  labels:
    app.kubernetes.io/name: teslamate
spec:
  secretName: teslamate-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - teslamate.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
