apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: teslamate
resources:
  - secret-store.yaml
  - certificate.yaml
  - middleware.yaml
  - tlsoption.yaml