apiVersion: apps/v1
kind: Deployment
metadata:
  name: abrp
  labels:
    app.kubernetes.io/name: abrp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: abrp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abrp
    spec:
      containers:
        - name: abrp
          image: docker.io/fetzu/teslamate-abrp:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          envFrom:
            - configMapRef:
                name: abrp-config-env
            - secretRef:
                name: abrp-secrets-env
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              cpu: 20m
              memory: 48Mi
