apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: abrp
  app.kubernetes.io/part-of: teslamate
resources:
  - secrets.yaml
  - deployment.yaml
