apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: abrp-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: abrp-secrets-env
    template:
      engineVersion: v2
      type: Opaque
      data:
        USER_TOKEN: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: secret/teslamate/abrp
        property: USER_TOKEN
