apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: docker.io/eclipse-mosquitto:latest
          imagePullPolicy: IfNotPresent
          command:
            - mosquitto
          args:
            - -c
            - /mosquitto/config/mosquitto.conf
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1883
            runAsGroup: 1883            
            capabilities:
              drop:
                - "ALL"
          ports:
            - containerPort: 1883
              protocol: TCP
            - name: wss
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: wss
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: wss
          resources:
            limits:
              memory: 64Mi
              cpu: 10m
            requests:
              cpu: 5m
              memory: 32Mi
      volumes:
        - name: config
          secret:
            secretName: mosquitto-conf
