apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mosquitto-secrets
    template:
      engineVersion: v2
      type: Opaque
      data:
        hass-bridge.conf: |
          # Bridge to HASS
          connection bridge-hass
          address {{ .host }}:{{ .port }}
          remote_username {{ .username }}
          remote_password {{ .password }}
          topic # both 0
          try_private false
  data:
    - secretKey: host
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: host
    - secretKey: port
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: port
    - secretKey: username
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: username
    - secretKey: password
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: password
