apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mosquitto-conf
    template:
      engineVersion: v2
      type: Opaque
      data:
        mosquitto.conf: |
          ### Listeners ###

          # MQTT, anon
          listener 1883
          allow_anonymous true
          
          # Websockets, anon
          listener 8080 127.0.0.1
          protocol websockets
          allow_anonymous true
          websockets_log_level 0

          # Bridge to HASS
          connection bridge-hass
          address {{ .host }}:{{ .port }}
          #bridge_capath /etc/ssl/certs
          #bridge_insecure true
          remote_username {{ .username }}
          remote_password {{ .password }}
          topic # both 0
          try_private false

          ### General ###

          # Logging
          log_timestamp_format %Y-%m-%dT%H:%M:%S
          log_type all
          log_dest stdout

          # Persistence
          persistence false
  data:
    - secretKey: host
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: host
    - secretKey: port
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: port
    - secretKey: username
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: username
    - secretKey: password
      remoteRef:
        key: secret/teslamate/mqtt-bridge
        property: password

